version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm i
            - run: npm run build
            - run: node dist/main PORT=80 APP_HOSTNAME=localhost:3000 LOG_LEVEL=debug ALLOWED_DOMAINS=http://localhost:8080,http://localhost:8081 ALLOWED_HEADERS=* DB_HOST=mongodb+srv://dbAdmin:QFb8WJpDdeWNZwCc@htn-cluster-lxa7j.mongodb.net DB_NAME=hospital ENABLE_SWAGGER=true NODE_ENV=development
workflows:
    build-and-test:
      jobs:
        - build-and-test
